FROM node:10 as builder
WORKDIR /frontend-app
COPY package*.json ./
RUN npm install 
COPY . .
RUN npm run build:production

FROM nginx 
COPY ./frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /frontend-app/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]