version: "3.8"
services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  backend:
    restart: on-failure
    container_name: inventory-backend
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
      - "/app/uploads"
    environment:
      - DBUSER=postgres
      - DBHOST=database-1.cdyzv1xisfen.ap-southeast-2.rds.amazonaws.com
      - DBNAME=inventory
      - DBPASSWORD=abc123456

  frontend:
    stdin_open: true
    restart: on-failure
    container_name: inventory-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
