FROM node:10
ENV DBHOST=postgres
ENV DBUSER=postgres
ENV DBPASS=
ENV DBNAME=inventory
WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . .
EXPOSE 8080
RUN mkdir -p /app/uploads
CMD ["npm", "run", "start:production"]
